services:
  svitlobot:
    build: .
    container_name: svitlobot
    command: python main.py
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Europe/Kyiv
    volumes:
      - ./data:/app/data
      - ./parser/data:/app/parser/data

  parser:
    build: .
    container_name: parser
    restart: always
    command: python run.py
    working_dir: /app/parser
    volumes:
      - ./data:/app/data
      - ./parser/data:/app/parser/data
    env_file:
      - .env
    environment:
      - TZ=Europe/Kyiv
      - PYTHONPATH=/app

